import { StyleSheet } from 'react-native';
import { Colors, Spacing } from '@/constants/theme';

// Shared by dashboard.tsx and all three path view components — the three
// paths' cards/stats/rows lean on the same design-system shapes closely
// enough that splitting this per-file would mean either duplicating most of
// it or fighting real cross-file sharing, so it stays as one stylesheet.
export const dashboardStyles = StyleSheet.create({
  scrollContent: {
    paddingBottom: 40,
  },
  stack: {
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.md,
    gap: 12,
  },
  card: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 18,
    padding: 17,
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  eyebrowGreen: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.success,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  eyebrowMuted: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  mono: {
    fontSize: 12.5,
    fontWeight: '700',
    color: Colors.textSecondary,
  },
  cardTitle: {
    fontSize: 16.5,
    fontWeight: '700',
    color: Colors.textPrimary,
    marginTop: 7,
    lineHeight: 21,
  },
  goalMeta: {
    fontSize: 13,
    color: Colors.textSecondary,
    marginTop: 4,
  },
  careerPct: {
    fontSize: 22,
    fontWeight: '800',
    color: Colors.success,
    letterSpacing: -0.4,
  },
  weeklyActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: Colors.offWhite,
    borderRadius: 12,
    padding: 12,
    marginTop: 13,
  },
  weeklyActionLabel: {
    fontSize: 10.5,
    fontWeight: '700',
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  weeklyActionTitle: {
    fontSize: 13.5,
    fontWeight: '600',
    color: Colors.textPrimary,
    marginTop: 2,
  },
  viewButton: {
    backgroundColor: Colors.infoSoft,
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 13,
  },
  viewButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.primaryLight,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 11,
  },
  statValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 5,
    marginTop: 7,
  },
  statValue: {
    fontSize: 27,
    fontWeight: '800',
    color: Colors.textPrimary,
    letterSpacing: -0.5,
  },
  statUnit: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  statNextTitle: {
    fontSize: 14.5,
    fontWeight: '700',
    color: Colors.textPrimary,
    marginTop: 7,
    lineHeight: 18,
  },
  statNextDate: {
    fontSize: 12.5,
    fontWeight: '700',
    color: Colors.warning,
    marginTop: 2,
  },
  statNextDateMuted: {
    fontSize: 12.5,
    fontWeight: '600',
    color: Colors.textSecondary,
    marginTop: 1,
  },
  examPill: {
    fontSize: 12,
    fontWeight: '700',
    paddingVertical: 4,
    paddingHorizontal: 9,
    borderRadius: 999,
    overflow: 'hidden',
  },
  weekTopic: {
    fontSize: 14.5,
    fontWeight: '600',
    color: Colors.textPrimary,
    marginTop: 11,
  },
  examTaskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  examTaskDot: {
    width: 17,
    height: 17,
    borderRadius: 8.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  examTaskTitle: {
    flex: 1,
    fontSize: 13.5,
    color: Colors.textSecondary,
  },
  examTaskMeta: {
    fontSize: 11.5,
    fontWeight: '700',
    color: Colors.primaryLight,
  },
  todayTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  classRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    backgroundColor: Colors.offWhite,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  classBar: {
    width: 4,
    alignSelf: 'stretch',
    borderRadius: 2,
  },
  classRowTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  classRowTime: {
    fontSize: 12.5,
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  classRowMeta: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 1,
  },
  syllabusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    backgroundColor: Colors.offWhite,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  syllabusIconBox: {
    width: 30,
    height: 30,
    borderRadius: 9,
    backgroundColor: Colors.infoSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noClassText: {
    fontSize: 13,
    color: Colors.textMuted,
    lineHeight: 18,
  },
  weekGoalTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.textPrimary,
    flex: 1,
    marginRight: 10,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: Colors.border,
    marginTop: 11,
    overflow: 'hidden',
  },
  upcomingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 13,
    paddingVertical: 11,
    paddingHorizontal: 13,
  },
  upcomingDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  upcomingTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    color: Colors.textPrimary,
  },
  upcomingDate: {
    fontSize: 12.5,
    fontWeight: '700',
    color: Colors.textSecondary,
  },
  coachCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    backgroundColor: Colors.textPrimary,
    borderRadius: 17,
    padding: 16,
  },
  coachIconBox: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  coachEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.6)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  coachText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.white,
    marginTop: 2,
    lineHeight: 19,
  },
  habitsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 17,
    padding: 15,
  },
  habitIconBox: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: Colors.warningSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  habitEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.warning,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  habitText: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.textPrimary,
    marginTop: 2,
  },
  quickLinksRow: {
    flexDirection: 'row',
    gap: 11,
  },
  quickLinkCard: {
    flex: 1,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 16,
    padding: 14,
  },
  quickLinkIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickLinkTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.textPrimary,
    marginTop: 10,
  },
  quickLinkSub: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 1,
  },
});
